# Generated by Django 5.2.3 on 2026-03-20 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plan_entrenamiento', 'Plan de entrenamiento'), ('plan_alimentacion', 'Plan de alimentación'), ('coach', 'Coach personal'), ('seguimiento', 'Seguimiento de progreso')], default='coach', max_length=50)),
                ('mensaje_usuario', models.TextField()),
                ('respuesta_ia', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
