# Generated by Django 5.2.3 on 2026-04-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_conversacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='agua_por_dia',
            field=models.FloatField(blank=True, help_text='Litros de agua al día', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='alergias',
            field=models.TextField(blank=True, help_text='Alergias alimentarias'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='calidad_sueno',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='comidas_por_dia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='condiciones_medicas',
            field=models.TextField(blank=True, help_text='Ej: diabetes, hipertensión'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dias_entrenamiento',
            field=models.PositiveIntegerField(blank=True, help_text='Días por semana', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lesiones',
            field=models.TextField(blank=True, help_text='Lesiones o limitaciones físicas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lugar_entrenamiento',
            field=models.CharField(blank=True, choices=[('casa', 'Casa'), ('gimnasio', 'Gimnasio'), ('ambos', 'Ambos')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='motivacion',
            field=models.CharField(blank=True, choices=[('salud', 'Salud'), ('estetica', 'Estética'), ('rendimiento', 'Rendimiento deportivo')], max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel_actividad',
            field=models.CharField(blank=True, choices=[('sedentario', 'Sedentario'), ('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel_estres',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='objetivo_tiempo',
            field=models.CharField(blank=True, help_text='Ej: bajar 5kg en 3 meses', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='restricciones_alimentarias',
            field=models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('vegetariano', 'Vegetariano'), ('vegano', 'Vegano'), ('sin_gluten', 'Sin gluten'), ('sin_lactosa', 'Sin lactosa'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tiempo_sesion',
            field=models.PositiveIntegerField(blank=True, help_text='Minutos por sesión', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tiene_equipo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('bajar_peso', 'Bajar de peso'), ('aumentar_masa', 'Aumentar masa muscular'), ('mantenerse', 'Mantenerse'), ('mejorar_resistencia', 'Mejorar resistencia'), ('rehabilitacion', 'Rehabilitación')], max_length=100),
        ),
    ]
