# Generated by Django 5.2.3 on 2026-04-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_agua_por_dia_usuario_alergias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planalimentacion',
            name='objetivo',
            field=models.CharField(max_length=500),
        ),
    ]
