# Generated by Django 5.2.3 on 2026-04-09 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_planalimentacion_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('series', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField()),
                ('descanso', models.CharField(help_text='Ej: 60 segundos', max_length=50)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden en la rutina')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutina_ejercicios', to='usuarios.planentrenamiento')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
