# Generated by Django 5.2.3 on 2026-04-19 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_planentrenamiento_activo_planentrenamiento_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='planalimentacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RutinaComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('momento', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('merienda', 'Merienda')], default='almuerzo', max_length=20)),
                ('calorias', models.IntegerField(default=0)),
                ('proteinas', models.FloatField(default=0)),
                ('carbohidratos', models.FloatField(default=0)),
                ('grasas', models.FloatField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutina_comidas', to='usuarios.planalimentacion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
