# Generated by Django 5.2.3 on 2026-04-19 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_planalimentacion_activo_rutinacomida'),
    ]

    operations = [
        migrations.AddField(
            model_name='planentrenamiento',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='sesiones_completadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('sesion_numero', models.PositiveIntegerField(help_text='Número de sesión dentro del plan')),
                ('notas', models.TextField(blank=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_actividad', to='usuarios.planentrenamiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_actividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('calorias_consumidas', models.PositiveIntegerField(blank=True, null=True)),
                ('nivel_cumplimiento', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20)),
                ('agua_consumida', models.FloatField(blank=True, help_text='Litros consumidos', null=True)),
                ('notas', models.TextField(blank=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progresos', to='usuarios.planalimentacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_alimentacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Alimentación',
                'verbose_name_plural': 'Progresos de Alimentación',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
