# Generated by Django 5.2.3 on 2026-04-19 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_planentrenamiento_completado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('ejercicio_actual', models.PositiveIntegerField(default=1, help_text='Orden del ejercicio en curso')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='usuarios.planentrenamiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de entrenamiento',
                'verbose_name_plural': 'Sesiones de entrenamiento',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('rutina_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rutinaejercicio')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_completados', to='usuarios.sesionentrenamiento')),
            ],
            options={
                'ordering': ['rutina_ejercicio__orden'],
            },
        ),
    ]
