# Generated by Django 5.2.3 on 2026-04-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_sesionentrenamiento_ejerciciosesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planalimentacion',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planalimentacion',
            name='dias_completados',
            field=models.PositiveIntegerField(default=0, help_text='Días con registro de cumplimiento'),
        ),
        migrations.AddField(
            model_name='planalimentacion',
            name='duracion_dias',
            field=models.PositiveIntegerField(default=30, help_text='Duración del plan en días'),
        ),
        migrations.AddField(
            model_name='planalimentacion',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutinacomida',
            name='ingredientes',
            field=models.TextField(blank=True, help_text='Lista de ingredientes con cantidades'),
        ),
        migrations.AddField(
            model_name='rutinacomida',
            name='preparacion',
            field=models.TextField(blank=True, help_text='Pasos para preparar la comida'),
        ),
        migrations.AddField(
            model_name='rutinacomida',
            name='tiempo_preparacion',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo en minutos'),
        ),
    ]
