# Generated by Django 5.2.3 on 2026-04-30 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_planalimentacion_completado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='racha_actual',
            field=models.PositiveIntegerField(default=0, help_text='Días consecutivos activos en la app'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='racha_maxima',
            field=models.PositiveIntegerField(default=0, help_text='Mejor racha histórica'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateField(blank=True, help_text='Último día que el usuario abrió la app', null=True),
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('entreno', models.BooleanField(default=False, help_text='Completó al menos una sesión de entrenamiento ese día')),
                ('cumplio_alimentacion', models.BooleanField(default=False, help_text='Registró cumplimiento de alimentación ese día')),
                ('nivel_alimentacion', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], help_text='Copia del nivel_cumplimiento de ProgresoAlimentacion para acceso rápido', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
