# Generated by Django 5.2.3 on 2026-05-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacceso',
            name='grupos_musculares',
            field=models.CharField(blank=True, help_text='Grupos musculares trabajados en la sesion del dia, separados por coma', max_length=500),
        ),
        migrations.AddField(
            model_name='rutinacomida',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de imagen del plato o comida', null=True),
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='descripcion_ia',
            field=models.TextField(blank=True, help_text='Descripción y técnica generada por IA'),
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de imagen o GIF del ejercicio', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='acepto_terminos',
            field=models.BooleanField(default=False, help_text='El usuario aceptó los términos y condiciones al registrarse'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(blank=True, choices=[('avatar_1', 'Avatar 1 — Corredor'), ('avatar_2', 'Avatar 2 — Levantador'), ('avatar_3', 'Avatar 3 — Yogui'), ('avatar_4', 'Avatar 4 — Ciclista'), ('avatar_5', 'Avatar 5 — Nadador'), ('avatar_6', 'Avatar 6 — Boxeador'), ('avatar_7', 'Avatar 7 — Escalador'), ('avatar_8', 'Avatar 8 — Bailarín')], default='avatar_1', help_text='Avatar predeterminado seleccionado por el usuario', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_acepto_terminos',
            field=models.DateTimeField(blank=True, help_text='Fecha en que aceptó los términos', null=True),
        ),
    ]
