# Generated by Django 5.2.3 on 2026-03-11 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id_comida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('calorias', models.IntegerField()),
                ('proteinas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('grasas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('objetivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEntrenamiento',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_entrenamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAlimentacion',
            fields=[
                ('id_plan_alimentacion', models.AutoField(primary_key=True, serialize=False)),
                ('calorias', models.IntegerField()),
                ('objetivo', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
